config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',

}



# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  #管理者側ルーティング
  namespace :admin do
    resources :reviews, only:[:index, :show, :edit, :update, :destroy] do
      resources :comments,only:[:destroy]
    end
    resources :customers, only:[:index, :show, :edit, :update]
    resources :tags, only:[:new, :create]
    get "homes/top"
    get "search_tag" => "reviews#search_tag"
    get "search" => "searches#search"
  end

  #会員側ルーティング
  namespace :public do
    get "comments/create"
    get "comments/destroy"
  end

  scope module: :public do
    post "guest_sign_in" => "customers#guest_sign_in"  #ゲストログイン
    get "search_tag" => "reviews#search_tag"
    get "search" => "searches#search"
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
      resources :comments,only:[:create,:destroy]
    end
    resources :customers, only:[:index, :show, :edit, :update, :new, :destroy] do
      member do
        get :favorite
      end
    end
    resources :tags, only:[:destroy, :new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :customer

  validates :comment, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com", name: "ゲスト") do |customer|
    customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :review

  validates_uniqueness_of :review_id, scope: :customer_id

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :review_tags,dependent: :destroy
  has_many :tags,through: :review_tags
  has_many :comments, dependent: :destroy

  validates :store_name, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :body, presence: true

  #検索機能
  def self.looks(search, word)
    @review = Review.where("store_name LIKE?","%#{word}%")
  end

#いいね機能
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

end

app/models/review_tag.rb
class ReviewTag < ApplicationRecord
  belongs_to :review
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :review_tags,dependent: :destroy, foreign_key: 'tag_id'
  # タグは複数の投稿を持つ　それは、post_tagsを通じて参照できる
  has_many :review,through: :review_tags

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
     before_action :authenticate_admin!
     before_action :set_customer, only: [:edit, :update, :show]

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @reviews = @customer.reviews
  end

  def edit
  end

  def update
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

private

  def customer_params
    params.require(:customer).permit(:profile_image, :name)
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end

end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
    redirect_to new_admin_tag_path
  end


  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customer_path(current_customer.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/customers/edit.html.erb
<!--会員情報編集ページ-->
<div class="container">
  <div class="row p-auto">
    <div class="w-100 rounded px-0 my-5 border">
      <div class="bg-light">
        <h5 class="p-4 mb-0 ml-5 font-weight-bold">Profile Editing</h5>
      </div>
      <div class="form-body p-4 col-8 mx-auto">
      <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
      <!--名前編集-->
      <div class="input-group mb-3 mt-4">
        <div class="mr-2"><%= f.label :name, "Name" %></div>
        <%= f.text_field :name, class:"form-control" %>
      </div>
      <!--プロフィール画像編集-->
      <div class="input-group mb-3 mt-4">
        <div class="mr-2"><%= f.label :profile_image, "Profile Image" %></div>
        <%= f.file_field :profile_image, accept: "image/*" %>
      </div>
      <div class="btn input-group mb-3 mt-4">
        <%= f.submit "編集" %>
      </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<!--管理者側の会員一覧ページ-->
<div class="container">
  <div class="row">
    <div class="mx-auto col-md-11">
      <table class="table table-striped">
        <h4 class="mt-5">会員一覧</h4>
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>プロフィール画像</th>
            <th>氏名</th>
            <th>メールアドレス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer|%>
          <tr>
            <td><%= customer.id %></td>
            <td><%= image_tag customer.get_profile_image(80,80),size: "100x100", style:"object-fit: cover;" %></td>
            <td><%= link_to customer.name, admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
          </tr>
          <% end %>
          <%= paginate @customers %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<!--管理者側の会員詳細ページ-->
<div class="container">
  <div class="row">
    <div class="col-md-11 mx-auto border mt-5">
      <h5 class="p-4 mb-0 ml-5 font-weight-bold">User page</h5>
      <div class="row p-4 mb-0 ml-5">
        <%= image_tag @customer.get_profile_image(100,100), class:"mt-3"; %>
        <div class="d-flex align-items-center ml-3"><%= @customer.name %></div>
        <div class="d-flex align-items-center ml-3"><%= link_to '編集', edit_admin_customer_path(@customer.id), method: :get %></div>
      </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">レビュー画像</th>
            <th scope="col">タグ</th>
            <th scope="col">名前</th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
          <tr>
            <td>
              <% if review.image.attached? %>
              <%= link_to admin_review_path(review.id) do %>
                <%= image_tag review.image, size: "200x200", class:"img-fluid"; %>
              <% end %>
              <% end %>
            </td>
            <td>
              <% review.tags.each do |tag| %>
                <span>#<%= tag.name %></span>
              <% end %>
            </td>
            <td><%= review.customer.name %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <% #link_to "編集", edit_review_path(review), class: "btn btn-success" %>
    </div>
  </div>
</div>