config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',

}



# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  #管理者側ルーティング
  namespace :admin do
    resources :reviews, only:[:index, :show, :edit, :update, :destroy] do
      resources :comments,only:[:destroy]
    end
    resources :customers, only:[:index, :show, :edit, :update]
    resources :tags, only:[:new, :create]
    get "homes/top"
    get "search_tag" => "reviews#search_tag"
    get "search" => "searches#search"
  end

  #会員側ルーティング
  namespace :public do
    get "comments/create"
    get "comments/destroy"
  end

  scope module: :public do
    post "guest_sign_in" => "customers#guest_sign_in"  #ゲストログイン
    get "search_tag" => "reviews#search_tag"
    get "search" => "searches#search"
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
      resources :comments,only:[:create,:destroy]
    end
    resources :customers, only:[:index, :show, :edit, :update, :new, :destroy] do
      member do
        get :favorite
      end
    end
    resources :tags, only:[:destroy, :new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :customer

  validates :comment, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com", name: "ゲスト") do |customer|
    customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :review

  validates_uniqueness_of :review_id, scope: :customer_id

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :review_tags,dependent: :destroy
  has_many :tags,through: :review_tags
  has_many :comments, dependent: :destroy

  validates :store_name, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :body, presence: true

  #検索機能
  def self.looks(search, word)
    @review = Review.where("store_name LIKE?","%#{word}%")
  end

#いいね機能
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

end

app/models/review_tag.rb
class ReviewTag < ApplicationRecord
  belongs_to :review
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :review_tags,dependent: :destroy, foreign_key: 'tag_id'
  # タグは複数の投稿を持つ　それは、post_tagsを通じて参照できる
  has_many :review,through: :review_tags

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_review, only: [:show, :edit, :update, :destroy]
  def index
    @reviews =Review.page(params[:page])
    @tags = Tag.all
  end

  def show
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to admin_review_path(@review)
    else
      render "edit"
    end
  end

  def destroy
    @review.destroy
    redirect_to admin_reviews_path, notice: "レビューを削除しました"
  end

  def search_tag
    @review_tags = ReviewTag.where(tag_id: params[:id])
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:body, :store_name, :longitude, :latitude, :image, :price, :address, tag_ids: [])
  end


end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @tag = Tag.new
    @tags = Tag.all
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
    redirect_to new_admin_tag_path
  end


  private

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customer_path(current_customer.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/favorites_helper.rb
module Admin::FavoritesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/reviews/edit.html.erb
<!--管理者側レビュー編集-->
<div class="p-md-5 mx-md-3 mx-md-auto">
  <div class="row">
    <div class="col-md-11 mx-auto rounded border">
      <div class="form-body p-4 col-8 mx-auto">
        <h5 class="mb-0">Review Editing</h5>
        <%=form_with model: @review, url: admin_review_path, method: :patch do |f| %>
        <div class="input-group mb-3 mt-4">
          <%= f.file_field :image, accept: "image/*" %>
        </div>
        <div class="input-group mb-3 mt-4">
          <%= f.text_area :body, class:"form-control", rows:"3", placeholder:"本文" %>
        </div>
        <div class="input-group mb-3 mt-4">
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <div class='form-check'>
            <%= tag.label class: 'form-check-label' do %>
              <%= tag.check_box class: 'form-check-input' %>
              <%= tag.text %>
            <% end %>
          </div>
        <% end %>
        </div>
        <div class="input-group mb-3 mt-4">
          <%= f.text_field :store_name, class:"form-control", placeholder:"ショップ名" %>
        </div>
        <div class="input-group mb-3 mt-4">
          <%= f.text_field :price, class:"form-control", placeholder:"価格" %>
        </div>
        <div class="input-group mb-3 mt-4">
          <%= f.text_field :address, class:"form-control", placeholder:"住所" %>
        </div>
        <hr>
        <div class="pb-3">
        <%= f.submit '編集', class:"btn btn-info mt-4" %>
        <%= link_to "削除", admin_review_path(@review.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger mt-4" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/index.html.erb
<!--管理者側のレビュー一覧ページ-->
<div class="container">
  <div class="row">
    <div class="mx-auto col-md-11">
      <table class="table table-striped">
          <h4 class="mt-5">レビュー一覧</h4>
        <thead>
          <tr>
            <th>ID</th>
            <th>レビュー画像</th>
            <th>タグ</th>
            <th>店名</th>
            <th>投稿者</th>
          </tr>
        </thead>
        <tbody>
          <% @reviews.each do |review| %>
          <tr>
            <th><%= review.id %></th>
            <td>
              <% if review.image.attached? %>
              <%= link_to admin_review_path(review.id) do %>
                <%= image_tag review.image, size: "200x200", class:"img-fluid"; %>
              <% end %>
              <% end %>
            </td>
            <td><% review.tags.each do |tag| %><span>#<%= tag.name %></span><% end %></td>
            <td><%= review.store_name %></td>
            <td>
              <%= link_to admin_customer_path(review.customer.id) do %>
                <%= review.customer.name %>
              <% end %>
            </td>
          </tr>
          <% end %>
          <%= paginate @reviews %>
        </tbody>
      </table>
      <div class="d-flex flex-wrap">
        <% @tags.each do |tag| %>
        <div class="btn rounded-pill m-1 border border-secondary tag-borderline">
          <%= link_to tag.name , admin_search_tag_path(id: tag.id), style:"color: #000;" %>
          <%="(#{tag.review.count})" %>
        </div>
        <% end %>
        <button class="btn rounded-pill m-1 border border-secondary tag-borderline"><%= link_to "新しいタグを作成する>>", new_admin_tag_path, style:"color: #000;" %></button>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/search_tag.html.erb
<!--管理者側タグのついた投稿を取り出す-->
<div class="container">
  <div class="row">
    <div class="col-md-11 mx-2 mx-sm-auto border rounded px-0 my-5">
      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
          <% @review_tags.each do |review_tags| %>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <%= link_to admin_review_path(review_tags.review.id) do %>
                <%= image_tag review_tags.review.image,size: "300x300", class: "card-img-top", style: "object-fit: cover;" %>
              <% end %>
              <div class="card-body">
                <div class="card-text favorite-btn" id="favorite-btn_<%= review_tags.review.id %>">
                  <%= render 'public/favorites/favorite-btn', review: review_tags.review %>
                </div>
                <p class="card-text">
                  <%= review_tags.review.store_name %>
                </p>

              </div>
            </div>
          </div>
        <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reviews/show.html.erb
<!--管理者側のレビュー詳細ページ-->
<div class="p-md-5 mx-md-3 mx-md-auto">
  <div class="row">
    <div class="col-md-11 mx-auto rounded border">
      <div class="col-md-8 mx-2 mx-auto">
        <!--会員プロフィール画像・名前-->
        <div class="card-title row mt-3">
          <%= image_tag @review.customer.get_profile_image(80,80), class:"rounded-circle mt-3 ml-3 profile-image" %>
          <div class="col-9"><%= link_to @review.customer.name ,admin_customer_path(@review.customer.id), class:"customer-name" %></div>
        </div>
      </div>
      <!--レビュー画像-->
      <% if @review.image.attached? %>
      <div class="row"><%= image_tag @review.image, class:"card-img-top col-8 mx-2 mx-auto" %></div>
      <% end %>
      <div class="col-8 mx-2 mx-auto mb-5">
        <!--いいね数-->
        <p class="card-text ">
          いいね数
          <%= @review.favorites.count %>
        </p>
        <!--店名-->
        <p class="card-text">
          店名
          <%= @review.store_name %>
        </p>
        <!--本文-->
        <p class="card-text">
          本文
          <%= @review.body %>
        </p>
        <!--タグ-->
        <p class="card-text">
          タグ
          <% @review.tags.each do |tag| %>
            <span><%= tag.name %></span>
          <% end %>
        </p>
        <!--価格-->
        <p class="card-text">
          価格
          <%= @review.price %>
        </p>
        <p class="card-text">
          住所
          <%= @review.address %>
        </p>
        <!--編集-->
        <%= link_to "編集", edit_admin_review_path(@review.id), class: "btn btn-info" %>
        <!--コメント-->
        <div class="my-4 border-top">コメント数：<%= @review.comments.count %></div>
        <table>
          <% @review.comments.each do |review_comment| %>
          <tr>
            <td><%= image_tag review_comment.customer.get_profile_image(80,80), class:"rounded-circle mr-2 profile-image" %>
            <%= link_to review_comment.customer.name , customer_path(review_comment.customer.id), class:"customer-name ml-4 mt-3" %></td>
            <td class="col-10"><%= review_comment.comment %></td>
            <td class="col-2"><%= link_to "コメント削除",  admin_review_comment_path(review_comment.review, review_comment), method: :delete,remote: true,class:"btn btn-danger", style: "font-size: xx-small;" %></td>
          </tr>
          <% end %>
        </table>

      </div>
    </div>
  </div>
</div>