config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',

}



# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  #管理者側ルーティング
  namespace :admin do
    resources :reviews, only:[:index, :show, :edit, :update, :destroy] do
      resources :comments,only:[:destroy]
    end
    resources :customers, only:[:index, :show, :edit, :update]
    resources :tags, only:[:new, :create]
    get "homes/top"
    get "search_tag" => "reviews#search_tag"
    get "search" => "searches#search"
  end

  #会員側ルーティング
  namespace :public do
    get "comments/create"
    get "comments/destroy"
  end

  scope module: :public do
    post "guest_sign_in" => "customers#guest_sign_in"  #ゲストログイン
    get "search_tag" => "reviews#search_tag"
    get "search" => "searches#search"
    resources :reviews do
      resource :favorites, only: [:create, :destroy]
      resources :comments,only:[:create,:destroy]
    end
    resources :customers, only:[:index, :show, :edit, :update, :new, :destroy] do
      member do
        get :favorite
      end
    end
    resources :tags, only:[:destroy, :new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :customer

  validates :comment, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: "guest@example.com", name: "ゲスト") do |customer|
    customer.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :review

  validates_uniqueness_of :review_id, scope: :customer_id

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :customer
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :review_tags,dependent: :destroy
  has_many :tags,through: :review_tags
  has_many :comments, dependent: :destroy

  validates :store_name, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :body, presence: true

  #検索機能
  def self.looks(search, word)
    @review = Review.where("store_name LIKE?","%#{word}%")
  end

#いいね機能
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

end

app/models/review_tag.rb
class ReviewTag < ApplicationRecord
  belongs_to :review
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :review_tags,dependent: :destroy, foreign_key: 'tag_id'
  # タグは複数の投稿を持つ　それは、post_tagsを通じて参照できる
  has_many :review,through: :review_tags

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    customer_path(current_customer.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer style="background-color: #D8BfD8;">
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #D8BfD8;">
    <div class="container">
        <!--管理者ログイン時ロゴ-->
        <% if admin_signed_in? %>
          <a class="navbar-brand" href="/admin/homes/top"><span><%= image_tag "cafelog-logo.png", size: "200x130" %></span></a>
        <!--会員ログイン時、未ログイン時ロゴ-->
        <% else %>
          <a class="navbar-brand" href="/"><span><%= image_tag "cafelog-logo.png", size: "200x130" %></span></a>
        <% end %>
        <!--ハンバーガーメニュー-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <!--会員ログイン時-->
        <% if customer_signed_in? %>
          <li>
            <%= link_to 'Reviews', reviews_path, class: "nav-link text-body" %>
          </li>
          <li>
            <%= link_to 'New Review', new_review_path(current_customer),class: "nav-link text-body" %>
          </li>
          <li>
            <%= link_to 'My Page', customer_path(current_customer),class: "nav-link text-body" %>
          </li>
          <li>
            <%= link_to 'Logout', destroy_customer_session_path, method: :delete, class: "nav-link text-body" %>

          </li>
        <!--管理者ログイン時-->
        <% elsif admin_signed_in? %>
          <li>
            <%= link_to 'レビュー一覧', admin_reviews_path, class: "nav-link text-body" %>
          </li>
          <li>
            <%= link_to '会員一覧', admin_customers_path, class: "nav-link text-body" %>
          </li-->
          <li>
            <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link text-body" %>
          </li>
        <!--未ログイン時-->
        <% else %>
          <li>
            <%= link_to '新規登録', new_customer_registration_path,class: "nav-link text-body" %>
          </li>
          <li>
            <%= link_to 'ログイン', new_customer_session_path ,class: "nav-link text-body" %>
          </li>
          <li>
            <%= link_to 'ゲストログイン', guest_sign_in_path, method: :post ,class: "nav-link text-body" %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe Log</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>